import Layout from "@/components/layout";
import Head from "next/head";
import Image from "next/image";
import profulePic from "../../public/images/profile/developer-pic-1.png";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex items-center text-dark w-full min-h-screen">
        <Layout className="pt-0">
          <div className="flex items-center justify-between">
            <div className="w-1/2">
              <Image src={profulePic} alt="image" className=" h-auto" />
            </div>
          </div>
        </Layout>
      </main>
    </>
  );
}
